Update pip-install.yml

diff --git a/.github/workflows/pip-install.yml b/.github/workflows/pip-install.yml
--- a/.github/workflows/pip-install.yml
+++ b/.github/workflows/pip-install.yml
@@ -31,22 +31,21 @@ jobs:
         run: |
           python -m pip install cibuildwheel==2.12.1
 
-      - name: Build wheels on Windows
-        if: runner.os == 'Windows'
-        run: python -m cibuildwheel --output-dir wheelhouse
-        env:
-          CIBW_BUILD: 'cp3?-win_amd64'
-          DISTUTILS_USE_SDK: 1
-          MSSdk: 1
-
-      - name: Build wheels on Mac and Linux
-        if: runner.os != 'Windows'
+      - name: Check if allowed operating system (Linux/Mac)
+        if: runner.os != 'Linux' || runer.os != 'macOS'
         run: |
-          python -m cibuildwheel --output-dir wheelhouse
+          echo "Cannot build on this operating system."
+          exit 1
+
+      - name: Build wheel
+        run: |
+          if [[ "$RUNNER_OS" == "Linux" ]]; then
+            CIBW_SKIP='*-manylinux_i686' CIBW_MANYLINUX_X86_64_IMAGE=manylinux2014 python -m cibuildwheel --output-dir wheelhouse
+          else
+            python -m cibuildwheel --output-dir wheelhouse
+          fi
         env:
           CIBW_BUILD: 'cp3?-*'
-          CIBW_SKIP: '*-manylinux_i686'
-          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
 
       - uses: actions/upload-artifact@v4
         with:
